# Promise

资料：尚硅谷_Promise核心技术

## 基础

### Promise 是什么 ？

1. 抽象表达

Promise 是 JS 中进行异步编程的新的解决方案

2. 具体表达

- 语法上：Promise 是一个构造函数
- 功能上：Promise 对象用来封装一个异步操作并可以获取其结果

### Promise 状态的改变

1. `pending` 变为 `resolved`

2. `pending` 变为 `rejected`

只有这两种，且一个 `promise` 对象只能改变一个，无论变为成功还是失败，都会有一个结果数据（成功一般称为 value，失败一般称为 reason）。

### Promise 基本流程

### Promise 的使用

1. `Promise` 构造函数： `Promise (excutor) {}`

excutor 函数：同步执行`(resolve, reject) => {}`

- resolve 函数：内部定义成功时我们调用的函数 `value => {}`
- reject 函数：内部定义失败时我们调用的函数 `reason => {}`

说明：excutor 会在 promise 内部立即同步回调，异步操作操作在执行器中执行

2. Promise.prototype.then 方法：`(onResolved, onReject) => {}`

- onResolved 函数： 成功的回调函数 `value => {}`
- onRejected 函数：失败的回调函数 `reason => {}`

说明：指定用于得到成功 value 的成功回调和用于得到失败 reason 的失败回调，`返回一个新的 promise 对象`

3. Promise.prototype.catch 方法：`onRejected => {}`

- onRejected 函数： 失败的回调函数`reason => {}`

说明：then() 的语法糖，相当于：`then(undefined, onRejected) => {}`

4. Promise.resolve 方法： `value => {}`

- value：成功的数据或 promise 对象

说明：返回一个成功或失败的 promise 对象

5. Promise.reject 方法： `reason => {}`

- value：失败的原因

说明：返回一个失败的 promise 对象


### 关键点

1. 如何改变`promise`的状态？

- resolve(value)：如果当前是`pending`就变为`resolved`
- reject(reason)：如果当前是`pending`就变为`rejected`
- `throw`抛出异常：如果当前是`pending`就会变为`rejected`

2. 一个`promise`指定多个成功或失败回调函数时，都会调用还是只调用最后一个？（答案：都会调用）

```javascript

const p = new Promise((resolve, reject) => resolve(1))

p.then(value => console.log(value))  // 1  
p.then(value => console.log(value))   // 1

```

3. 改变`promise`状态和指定回调函数谁先谁后？

都有可能，正常情况下是先指定回调再改变状态，但也可以先改变状态再指定回调

1）如何先改变状态再指定回调？
- 在执行器中值直接调用`resolve()`或`reject()`
- 延迟更长时间才调用`then()`

2) 什么时候才能得到数据？
- 如果先指定的回调，那当状态发生改变时，回调函数就会调用，得到数据
- 如果先改变的状态，那当指定回调时，回调函数就会调用，得到数据

## 实现

### Promise/Promise.then/catch

// TODO 一些注意点...

```javascript
(function (window) {
  const PENDING = 'pending';
  const RESOLVED = 'resolved';
  const REJECTED = 'rejected';
  /**
   * Promise 构造函数
   * excutor 执行器函数，同步执行
   */
  function Promise(excutor) {
    const self = this;
    //状态，默认 pending
    this.status = PENDING;
    //数据
    this.data = undefined;
    //存放 .then 内待执行的异步回调函数，包含元素 {onResolved(value) {}, onRejected(reason) {}}
    this.callbacks = [];
    
    //成功回调
    function resolve(value) {
      // 状态不可逆
      if (self.status !== PENDING) return;
      //更改状态
      self.status = RESOLVED;
      //更改数据
      self.data = value;
      /**
       * 1.如果有待执行的 callback 函数，立即异步执行回调函数 onResolved 
       * 说明：有待执行（不一定有，看是先改变状态还是先执行.then内的回调）的 callback 函数是因为执行器内有异步函数导致「resolve()或reject()」被放到了队列中未立即执行，
       *      接着执行同步代码到「.then」时，由于状态仍是 pending 状态，而无法判断执行 onResolved 还是 onRejected，所以先把这两个回调添加到了待执行的 callback 数组中
       *      等到执行异步「resolve()或reject()」时，再去执行 callbacks 中对应的成功或失败的回调函数
       */
      if (self.callbacks.length > 0) {
        setTimeout(() => {
          // 放入队列中执行所有成功的回调
          self.callbacks.forEach(callbackObj => {
            callbackObj.onResolved(value);
          })
        })
      }
    }

    // 失败回调
    function reject(reason) {
      if (self.status !== PENDING) return;
      self.status = REJECTED;
      self.data = reason;

      // 如果有待执行的 callback 函数，立即 “异步” 执行回调函数 onRejected
      if (self.callbacks.length > 0) {
        setTimeout(() => {
          // 放入队列中执行所有失败的回调
          self.callbacks.forEach(callbackObj => {
            callbackObj.onRejected(reason);
          })
        })
      }
    }

    // 如果使用时抛出异常了，则状态变为失败状态 rejeced
    try {
      excutor(resolve, reject);
    } catch (error) {
      reject(error);
    }
  }

  /**************************** Promise.prototype.then ****************************/

  /**
   * Promise 原型函数 then
   * then：同步执行，then 里边的回调异步执行
   * 指定成功和失败的回调函数
   * 返回一个新的 Promise
   */
  Promise.prototype.then = function (onResolved, onRejected) {
    const self = this;
    // onResolved 默认处理
    onResolved = typeof onResolved === 'function' ? onResolved : value => value; //向后传递成功的value
    // 实现异常传透：指定默认的失败回调
    onRejected = typeof onRejected === 'function' ? onRejected : reason => { throw reason };
    
    // 返回一个新的 Promise
    return new Promise((resolve, reject) => {
      // 调用指定回调函数处理，根据执行结果改变 return 的 Promise 的状态
      function handle(callback) {
        try {
          // 执行回调的结果
          const result = callback(self.data);
          if (result instanceof Promise) {
            // 情况1：如果回调函数返回的「是 Promise」，return 的 Promise 结果就是这个 Promise 的结果
            // result.then(value => resolve(value), reason => reject(reason));
            result.then(resolve, reject);
          } else {
            // 情况2：如果回调函数返回「非 Promise」，return 的 Promise 就会成功，value 就是返回的值
            resolve(result);
          }
        } catch (error) {
          // 情况3：如果抛出异常，return 的 Promise 就会失败，reason 的值就是 error
          reject(error);
        }
      }

      if (this.status === PENDING) {
        /**
         * 1. .then 不负责改变 Promise 状态
         * 2. 因为 Promise.then 是同步执行，
         * 当 Promise 状态未改变时（如执行器内有异步回调时），then 无法判断是执行成功还是失败的回调，
         * 那么就要先把回调函数先保存起来，等状态发生改变的时候再去执行 onResolved 或 onRejected 并根据它的返回值改变 return 的 Promise 状态
         */
        this.callbacks.push({
          onResolved() {
            handle(onResolved)
          },
          onRejected() {
            handle(onRejected)
          }
        })
      } else if (this.status === RESOLVED) {
        // resolved 状态时：异步（.then 内的回调函数属于微任务）执行 onResolved 并改变 return 的 Promise 的状态
        setTimeout(() => handle(onResolved));
      } else {
        // reject 状态时：异步执行 onRejected 并改变 return 的 Promise 的状态
        setTimeout(() => handle(onRejected));
      }
    })
  }

  /**************************** Promise.prototype.catch ****************************/
  /**
   * Promise 原型函数 catch
   */
  Promise.prototype.catch = function (onRejected) {
    return this.then(undefined, onRejected);
  }
  window.Promise = Promise;
})(window)

```

#### 验证

```javascript
const p = new Promise((resolve, reject) => {
      resolve(1);
    })
      .then(
        value => {
          console.log('onResolved1()', value);   //1
          return '第一个then传过来的值';
        }
      )
      .then(
        value => {
          console.log('onResolved2()', value); //第一个then传过来的值
          return new Promise((resolve, reject) => { reject('失败啦！') })
        }
      )
      .then(
        value => {
          console.log('onResolved3()', value);
        }
      )
      .catch(error => {
        console.log(error);  //失败啦！
      })
```

### Promise.all 

[传送门：Promise.all](http://es6.ruanyifeng.com/#docs/promise#Promise-all)


`Promise.all` 用于将多个`Promise`实例包装成一个新的`Promise`实例，如：

`const p = Promise.all([p1, p2, p3]);`

#### 注意

p的状态由 p1、p2、p3 决定，分成两种情况。

- p1、p2、p3 的状态都变成`fulfilled`，p 的状态才会变成`fulfilled`，此时 p1、p2、p3 的返回值会`按传入实例的顺序`组成一个数组，传递给 p 的回调函数。

- 只要 p1、p2、p3 之中有一个被`rejected`，p 的状态就变成`rejected`，此时第一个被`reject`的实例的返回值，会传递给p的回调函数。

#### 实现

```javascript
Promise.all = function (promises) {

  // 保存成功的次数
  let resolvedCount = 0;
  // 创建数组按顺序保存所有 promise 返回的值
  let values = new Array(promises.length);

  return new Promise((resolve, reject) => {
    promises.forEach((p, index) => {
      p.then(
        value => {
          resolvedCount++; 

          //按顺序存入所有 promise 对应的 value
          values[index] = value;  

          // 所有 promise 成功即成功，否则失败
          if (resolvedCount === promises.length) {
            resolve(values);
          }
        },
        reason => {
          // 如果有一个 promise 失败，则失败
          reject(reason);
        }
      )
    })
  })
}
```

#### 验证

```javascript

const p1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve(1)
  }, 2000)
})
const p2 = Promise.resolve(2)
// const p3 = Promise.reject(3);

Promise.all([p1, p2]).then(
  values => {
    console.log('------- 成功了 ---------');
    console.log(values)
  },
  reason => {
    console.log('------- 失败了 ---------');
    console.log(reason)
  }
)
```

输出：[1, 2]

### Promise.race

[传送门](http://es6.ruanyifeng.com/#docs/promise#Promise-race)

`Promise.race()` 方法将多个`Promise`实例，包装成一个新的 `Promise`实例。如：

`const p = Promise.race([p1, p2, p3]);`

#### 注意

只要 p1、p2、p3 中有一个实例`率先改变状态`，p 的状态就跟着改变。那个率先改变的 Promise 实例的返回值，就传递给 p 的回调函数。

#### 实现

```javascript

Promise.race = function (promises) {
  return new Promise((resolve, reject) => {
    promises.forEach((p, index) => {
      p.then(
        value => {
          // 如果谁最先成功， 即返回该 promise 的值
          resolve(value);
        },
        reason => {
          reject(reason);
        }
      )
    })
  })
}
```

#### 验证

```javascript

onst p1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve(1)
  }, 2000)
})
const p2 = Promise.resolve(2)
// const p3 = Promise.reject(3);


Promise.race([p1, p2]).then(
  values => {
    console.log('------- 成功了 ---------');
    console.log(values)
  },
  reason => {
    console.log('------- 失败了 ---------');
    console.log(reason)
  }
)

```

输出：2

### Promise.resolve/reject

[Promise.resolve 传送门](http://es6.ruanyifeng.com/#docs/promise#Promise-resolve)

[Promise.reject 传送门](http://es6.ruanyifeng.com/#docs/promise#Promise-reject)

#### 实现 Promise.resolve

```javascript

/**
 * Promise 函数对象的 resolve 方法
 * 返回值：一个指定结果的成功的 promise
 */
Promise.resolve = function (value) {
  return new Promise((resolve, reject) => {
    //value 是 promise 的时候,使用 value 的结果作为 promise 的结果
    if (value instanceof Promise) {
      value.then(resolve, reject);
    } else {
      resolve(value);
    }
  })
}
```

#### 实现 Promise.reject

```javascript
/**
 * Promise 函数对象的 reject 方法
 * 返回值：一个指定 reason 的失败的 promise
 */
Promise.reject = function (reason) {
  return new Promise((resolve, reject) => {
    reject(reason)
  })
}
```

#### 验证

```javascript

// 如果是一般值：p1 成功时，value 就是这个值
const p1 = Promise.resolve(1);
// 如果是成功的promise：p2 成功时，value 就是这个 promise 的 value
const p2 = Promise.resolve(Promise.resolve(2));
// 如果是失败的promise：p3 成功时，value 就是这个 promise 的 reason
const p3 = Promise.resolve(Promise.reject(3));
const p4 = Promise.reject(4);

p1.then(value => {
  console.log(value)   //1
})

p2.then(value => {
  console.log(value)  //2
})

p3.catch(value => {
  console.log(value)  //3
})

p4.catch(value => {
  console.log(value)  //4
})

```








